pod 'AFNetworking', '~> 3.0.4'
pod 'Masonry', '~> 0.6.4'
pod 'FMDB', '~> 2.6'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'RFQuiltLayout', '~> 1.1.1'
pod 'MOBFoundation_IDFA'
pod 'SMSSDK'
pod 'ShareSDK3', '~> 3.2.5'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'

pod 'SVProgressHUD'  